version: '3.8'
services:
  client:
    build: statistic/client/
    ports:
      - "9090:9090"
    depends_on:
      - server
    environment:
      - SERVER_URL=http://server:8080

  server:
    build: statistic/server/
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root


  db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explorewithme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
